"""
PDF report generation for legal document analysis results.
"""

from datetime import date

from fpdf import FPDF

# latin-1 replacements for common Unicode chars fpdf built-in fonts can't handle
_UNICODE_MAP = str.maketrans({
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2018": "'",   # left single quote
    "\u2019": "'",   # right single quote
    "\u201c": '"',   # left double quote
    "\u201d": '"',   # right double quote
    "\u2026": "...", # ellipsis
    "\u00a0": " ",   # non-breaking space
})


def _s(text: str) -> str:
    """Sanitize text to latin-1 safe characters."""
    return text.translate(_UNICODE_MAP).encode("latin-1", errors="replace").decode("latin-1")


RISK_COLORS = {
    "high":   (200, 50,  50),
    "medium": (210, 140, 0),
    "low":    (40,  150, 60),
    "none":   (100, 100, 100),
}

RISK_LABELS = {
    "high":   "HIGH RISK",
    "medium": "MEDIUM RISK",
    "low":    "LOW RISK",
    "none":   "NO ISSUES",
}


def generate_report(filename: str, clauses: dict, risks: dict, clause_labels: dict) -> bytes:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "Legal Document Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 6, _s(f"Document: {filename}"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 6, _s(f"Generated: {date.today().strftime('%B %d, %Y')}"), new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Overall risk banner ─────────────────────────────────────────────────
    overall = risks.get("overall", {})
    if overall:
        level = overall.get("level", "low")
        r, g, b = RISK_COLORS.get(level, (100, 100, 100))
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 12)
        label = RISK_LABELS.get(level, level.upper())
        pdf.cell(0, 10, _s(f"Overall Assessment: {label}"), new_x="LMARGIN", new_y="NEXT", fill=True, align="C")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(pdf.epw, 6, _s(overall.get("summary", "")))
        pdf.ln(8)

    # ── Divider ─────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Clause-by-Clause Analysis", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)

    # ── Each clause ─────────────────────────────────────────────────────────
    for key, label in clause_labels.items():
        clause = clauses.get(key, {})
        risk = risks.get(key, {})
        risk_level = risk.get("level", "none")
        r, g, b = RISK_COLORS.get(risk_level, (100, 100, 100))
        risk_label = RISK_LABELS.get(risk_level, "")

        # Clause title + risk badge
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(120, 7, _s(label), new_x="RIGHT", new_y="TOP")
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 7, _s(risk_label), new_x="LMARGIN", new_y="NEXT", align="R")
        pdf.set_text_color(0, 0, 0)

        # Summary
        if clause.get("found"):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(pdf.epw, 5, _s(clause.get("summary", "")))

            if clause.get("quote"):
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(80, 80, 80)
                quote = clause["quote"]
                if len(quote) > 200:
                    quote = quote[:200] + "..."
                pdf.multi_cell(pdf.epw, 5, _s(f'"{quote}"'))
                pdf.set_text_color(0, 0, 0)
        else:
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 5, "Not found in document", new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

        # Risk reason
        if risk.get("reason"):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(r, g, b)
            pdf.multi_cell(pdf.epw, 5, _s(f"Risk note: {risk['reason']}"))
            pdf.set_text_color(0, 0, 0)

        pdf.ln(5)
        pdf.set_draw_color(230, 230, 230)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    # ── Footer ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(180, 180, 180)
    pdf.cell(0, 5, "Generated by Legal Document Analyzer - github.com/chaser940428-pixel/legal-doc-analyzer", align="C")

    return bytes(pdf.output())
